spring:
    application:
        name: products
    
    datasource:
        url: jdbc:h2:file:./data/products
        driver-class-name: org.h2.Driver
        username: sa
        password:
    jpa:
        hibernate:
            ddl-auto: update
        database-platform: org.hibernate.dialect.H2Dialect

server:
    port: 9090
