name: Java Backend Tests

on:
  push:
    branches: [ "master" ]
    paths: 
      - 'products/**'
  pull_request:
    branches: [ "master" ]
    paths: 
      - 'products/**'

defaults:
  run:
    working-directory: ./products

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 24
      uses: actions/setup-java@v4
      with:
        java-version: '24'
        distribution: 'temurin'
        cache: maven
    - name: Run Backend Tests with Maven
      run: mvn -B test
